---
- name: Find vmoptions files
  find:
    paths: '{{ phpstorm_install_path }}/bin'
    patterns: '*.vmoptions'
  register: phpstorm_vmoptions_files
  become: '{{ phpstorm_privileged_install }}'

- name: Disable PhpStorm update checks
  lineinfile:
    path: '{{ item.path }}'
    regexp: '^-Dide\.no\.platform\.update'
    line: '-Dide.no.platform.update=true'
  with_items: '{{ phpstorm_vmoptions_files.files }}'
  become: '{{ phpstorm_privileged_install }}'
