---
- name: Provide python2 for the commandline launcher on Debian systems
  action: >
    {{ ansible_pkg_mgr }} name={{ item }} state=present update_cache=yes
  with_items:
    - python
  when: ansible_facts['os_family'] == "Debian"

- name: Provide python2 for the commandline launcher on RedHat systems
  action: >
    {{ ansible_pkg_mgr }} name={{ item }} state=present update_cache=yes
  with_items:
    - python2
  when: ansible_facts['os_family'] == "RedHat"

- name: Make python2 default
  alternatives:
    name: python
    path: /usr/bin/python2